# Generated by Django 6.0.4 on 2026-05-17 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
